### ISSUE TITLE
Modules: Popular posts and Related Pages

### ISSUE THREAD

**Issue by rd012a** [dave-yang/bono.cms#10]
I'm looking for cms a modular system, with such plug-ins, both for wordpress
1. Popular posts
https://wordpress.org/plugins/top-10/screenshots/
2. Related Posts
https://ru.wordpress.org/plugins/related-posts-thumbnails/screenshots/

You are planning to in the future, do such plug-ins ?

**Comment by dave-yang** [comment]
Yes, I was thinking about this as well. The ability to attach popular posts and related ones (in News/Blog modules) will be added in next version, which will be ready soon.
